# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef0dda8e41b256096330c64d0338a100021446b0f73b909e1730d761c67e198609afea13111140e8a22ff466072f454c7f35e521c6cd68c79ab5b7a918e3d0ad

test:
  secret_key_base: 3b4930522432ec172c73876b539e31d7bbcec94f4f180ebe01471d3890c3846018d562622b9314a281482a19efe29d9dbe96a31da4e2765047b7be5296ad6021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
